<?php

namespace Febis\SimpleTca\Data;

use TYPO3\CMS\Core\SingletonInterface;

class TcaDefinitionData implements SingletonInterface
{
    /** @var Table[] $tables */
    protected array $tables = [];

    public function hasTable(string $identifier): bool
    {
        return isset($this->tables[$identifier]);
    }

    /**
     * @return $this
     */
    public function addTable(Table $table, string $identifier)
    {
        if ($this->hasTable($identifier)) {
            $this->tables[$identifier]->mergeWithOverrideTable($table);
        } else {
            $this->tables[$identifier] = $table;
        }

        return $this;
    }

    /**
     * @return $this
     */
    public function removeTable(string $identifier)
    {
        if (null !== $this->tables[$identifier] ?? null) {
            unset($this->tables[$identifier]);
        }

        return $this;
    }

    public function getTable(string $identifier): ?Table
    {
        return $this->tables[$identifier] ?? null;
    }

    public function getTables(): array
    {
        return $this->tables;
    }

    /**
     * @return $this
     */
    public function clearTables()
    {
        $this->tables = [];

        return $this;
    }

    /**
     * @return String[]
     */
    public function getSqlArray(): array
    {
        $stmts = [];
        foreach ($this->tables as $name => $table) {
            $stmt = "### Generated by SimpleTCA ### \nCREATE TABLE `$name` (";
            foreach ($table->getFields() as $fieldName => $field) {
                /** @var Field $field */
                $stmt .= " `$fieldName` $field->type DEFAULT " . (
                    $field->default !== 0 && empty($field->default) ?
                        "''" :
                        $field->default
                    ) . " NOT NULL,";
            }
            $stmt .= ");";
            $stmts[] = $stmt;
        }
        return $stmts;
    }
}
