default:

workflow:
    rules:
        -
            if: $CI_COMMIT_TAG
        -
            if: $CI_COMMIT_BRANCH

stages:
    - install
    - lint
    - test
    - release

.php:
    image: thecodingmachine/php:8.3-v4-cli
    cache:
        key: php
        policy: pull
        paths:
            - vendor/

.php-lint:
    extends: .php
    stage: lint

.php-test:
    extends: .php
    stage: test

install:php:
    extends: .php
    stage: install
    cache:
        policy: pull-push
    script:
        - composer install --ignore-platform-reqs
    artifacts:
        paths:
            - bin

lint:phpecs:
    extends: .php-lint
    script:
        - composer lint:phpecs

lint:phpmd:
    extends: .php-lint
    script:
        - composer lint:phpmd

lint:phplint:
    extends: .php-lint
    script:
        - composer lint:phplint

lint:phpstan:
    extends: .php-test
    script:
        - composer test:phpstan

lint:rector:
    extends: .php-test
    script:
        - composer test:rector:dry

release:package:
    image: alpine
    stage: release
    script:
        - apk add curl
        - 'curl --show-error --fail --request POST --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
    only:
        - tags
