<?php

namespace Febis\SimpleTca;

use Febis\SimpleTca\Data\ItemConfig;
use Febis\SimpleTca\Data\TcaDefinitionData;
use Febis\SimpleTca\Data\TsConfig\FceGroup;
use Febis\SimpleTca\Data\TsConfig\TsConfigDataHandling;
use Febis\SimpleTca\Data\Typoscript\TyposcriptDataHandling;
use Febis\SimpleTca\Exception\CacheInstanceException;
use Febis\SimpleTca\Exception\CallstackExtractionException;
use Febis\SimpleTca\Exception\TsConfigExistsException;
use Febis\SimpleTca\FceGenerator\FceGenerator;
use Febis\SimpleTca\FceGenerator\Showitem\Mode;
use Febis\SimpleTca\TcaBuilder\TcaBuilder;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class TcaGenerator extends ShortcutImplementation
{
    use ConfigTrait;

    protected static ?TcaDefinitionData $tcaDefinitionDataInstance = null;

    protected static ?TsConfigDataHandling $tsConfigData = null;

    protected static ?TyposcriptDataHandling $typoscriptData = null;

    protected static ?ItemConfig $tmpItemConfig = null;

    private function __construct()
    {
    }

    /**
     * @throws CallstackExtractionException
     */
    public static function createTca(
        string $table = null,
        bool $activateLanguage = true,
        bool $activateSorting = true,
        bool $activateEnableColumns = true,
    ): TcaBuilder {
        return new TcaBuilder(
            $table ?? static::getConfig()->getTablename(),
            $activateLanguage,
            $activateSorting,
            $activateEnableColumns,
        );
    }

    /**
     * @throws CallstackExtractionException
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     * @SuppressWarnings(PHPMD.BooleanArgumentFlag)
     * @param bool $autogenerateDataProcessors only available if typoscript is also generated
     */
    public static function createFCE(
        string $identifier,
        string $cTypeLabel = '',
        string $icon = '',
        string $description = '',
        array $palettes = [],
        array $columns = [],
        string $showItem = '',
        Mode $showitemMode = Mode::Default,
        array $columnsOverrides = [],
        bool $autogenerateTyposcript = true,
        bool $autogenerateTsConfig = true,
        bool $autogenerateDataProcessors = true,
        string $tsConfigFceGroupIdentifier = null,
    ): FceGenerator {
        self::getConfig()->setTablename('tt_content');
        $extKey = self::getConfig()->getExtkey();
        $tsConfigFceGroupIdentifier ??= self::getConfig()->get('tsConfigFceGroup')
        ?? 'default';
        self::$tmpItemConfig = GeneralUtility::makeInstance(ItemConfig::class, $identifier);

        return GeneralUtility::makeInstance(
            FceGenerator::class,
            $extKey,
            $identifier,
            $cTypeLabel,
            $icon,
            $description,
            $palettes,
            $columns,
            $showItem,
            $showitemMode,
            $columnsOverrides,
            $autogenerateTsConfig,
            $autogenerateTyposcript,
            $autogenerateDataProcessors,
            $tsConfigFceGroupIdentifier,
        );
    }

    /**
     * @throws TsConfigExistsException
     * @throws CacheInstanceException
     */
    public static function overrideDefaultTsConfigFceGroup(string $header, string $show = '*'): void
    {
        static::getTsConfigData()->addFceGroup('default', new FceGroup('default', $header, $show), true);
    }

    /**
     * @throws TsConfigExistsException
     * @throws CacheInstanceException
     */
    public static function addFceGroup(string $identifier, string $header, string $show = '*'): void
    {
        static::getTsConfigData()->addFceGroup($identifier, new FceGroup($identifier, $header, $show), true);
    }

    public static function getTcaDefinitionDataInstance(): TcaDefinitionData
    {
        if (!static::$tcaDefinitionDataInstance instanceof TcaDefinitionData) {
            static::$tcaDefinitionDataInstance = GeneralUtility::makeInstance(TcaDefinitionData::class);
        }

        return static::$tcaDefinitionDataInstance;
    }

    /**
     * @throws TsConfigExistsException
     * @throws CacheInstanceException
     */
    public static function getTsConfigData(): TsConfigDataHandling
    {
        if (!static::$tsConfigData instanceof TsConfigDataHandling) {
            static::$tsConfigData = GeneralUtility::makeInstance(TsConfigDataHandling::class);

            if (!static::$tsConfigData->hasFceGroup('default')) {
                static::$tsConfigData->addFceGroup('default', new FceGroup('default', 'Default'));
            }
        }

        return static::$tsConfigData;
    }

    public static function getTyposcriptData(): TyposcriptDataHandling
    {
        if (!static::$typoscriptData instanceof TyposcriptDataHandling) {
            static::$typoscriptData = GeneralUtility::makeInstance(TyposcriptDataHandling::class);
        }

        return static::$typoscriptData;
    }

    public static function getItemConfig(): ItemConfig
    {
        return static::$tmpItemConfig;
    }

    public static function resetItemConfig(): void
    {
        static::$tmpItemConfig = null;
    }

    /**
     * @throws CallstackExtractionException
     */
    public static function translate(string $key): string
    {
        $conf = static::getConfig();

        $identifier = '';
        if ((self::$tmpItemConfig?->identifier ?? '') !== '') {
            $identifier = self::$tmpItemConfig->identifier . '.';
        }

        return $conf->ll() . $conf->getTablename() . '.' . $identifier . $key;
    }

    /**
     * @throws CallstackExtractionException
     */
    public function setDefaultLocalizationFile(string $filename)
    {
        self::getConfig()->setDefaultLocalizationFile($filename);
    }
}
