services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    simpletca_tsconfig.cache:
        class: TYPO3\CMS\Core\Cache\Frontend\PhpFrontend
        # We can not use CacheManager, as it can not be
        # injected/instantiated during ext_localconf.php loading
        # factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
        # therefore we use the static Bootstrap::createCache factory instead.
        factory: [ 'TYPO3\CMS\Core\Core\Bootstrap', 'createCache' ]
        arguments: [ 'simpletca_tsconfig' ]

    simpletca_typoscript.cache:
        class: TYPO3\CMS\Core\Cache\Frontend\PhpFrontend
        # We can not use CacheManager, as it can not be
        # injected/instantiated during ext_localconf.php loading
        # factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
        # therefore we use the static Bootstrap::createCache factory instead.
        factory: [ 'TYPO3\CMS\Core\Core\Bootstrap', 'createCache' ]
        arguments: [ 'simpletca_typoscript' ]

    Febis\SimpleTca\Data\TsConfig\TsConfigData:
        arguments: [ '@simpletca_tsconfig.cache' ]
        public: true

    Febis\SimpleTca\Data\Typoscript\TyposcriptData:
        arguments: [ '@simpletca_typoscript.cache' ]
        public: true

    Febis\SimpleTca\Utility\CallStackExtractor:
        public: true

    Febis\SimpleTca\EventListener\TcaGeneratorBuildTca:
        tags:
            -   name: event.listener
                identifier: 'simpletca-tcagenerator-build-tca'
                event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
                before: 'nr-rte-softref-enforcer'
    Febis\SimpleTca\EventListener\FcePageTsConfig:
        tags:
            -   name: event.listener
                identifier: 'simpletca-fcegenerator-generate-tsconfig'
                event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\ModifyLoadedPageTsConfigEvent
    Febis\SimpleTca\EventListener\TypoScriptLoader:
        tags:
            -   name: event.listener
                identifier: 'simpletca-typoscriptloader'
                event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\AfterTemplatesHaveBeenDeterminedEvent
