<?php

declare(strict_types=1);

namespace Febis\SimpleTca\FceGenerator;

use Febis\SimpleTca\Data\TsConfig\FceGroup;
use Febis\SimpleTca\Data\TsConfig\FceItem as TsConfigItem;
use Febis\SimpleTca\Data\Typoscript\FceItem as TyposcriptItem;
use Febis\SimpleTca\Exception\CacheInstanceException;
use Febis\SimpleTca\Exception\InvalidKeyException;
use Febis\SimpleTca\Exception\NoIdentifierException;
use Febis\SimpleTca\Exception\TsConfigExistsException;
use Febis\SimpleTca\Exception\TyposcriptExistsException;
use Febis\SimpleTca\FceGenerator\Showitem\Mode;
use Febis\SimpleTca\Shortcut\AbstractShortcut;
use Febis\SimpleTca\Shortcut\FileShortcut;
use Febis\SimpleTca\TcaGenerator;
use Febis\SimpleTca\Utility\DataProcessorUtility;
use TYPO3\CMS\Core\Utility\ArrayUtility;
use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;
use TYPO3\CMS\Extbase\Utility\DebuggerUtility;

/**
 * @TODO Refactor, split responsibilities into separate classes
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.TooManyPublicMethods)
 * @SuppressWarnings(PHPMD.ExcessiveClassComplexity)
 */
class FceGenerator
{
    final protected const string CONTENT_TABLE = 'tt_content';

    final protected const array FIELDS = [
        'rowDescription' => 'rowDescription,',
        'categories' => 'categories,',
    ];

    final protected const array PALETTES = [
        'general' => '--palette--;;general,',
        'headers' => '--palette--;;headers,',
        'frames' => '--palette--;;frames,',
        'appearanceLinks' => '--palette--;;appearanceLinks,',
        'hidden' => '--palette--;;hidden,',
        'access' => '--palette--;;access,',
        'language' => '--palette--;;language,',
    ];

    final protected const array TABS = [
        'general' => '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:general,',
        'appearance' => '--div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.appearance,',
        'access' => '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:access,',
        'notes' => '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:notes,',
        'extended' => '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:extended,',
        'language' => '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:language,',
        'categories' => '--div--;LLL:EXT:core/Resources/Private/Language/Form/locallang_tabs.xlf:categories,',
    ];

    final protected const array JOINED = [
        'generalPrepend' => self::TABS['general'] . self::PALETTES['general'] . self::PALETTES['headers'],
        'appearance' => self::TABS['appearance'] . self::PALETTES['frames'] . self::PALETTES['appearanceLinks'],
        'access' => self::TABS['access'] . self::PALETTES['hidden'] . self::PALETTES['access'],
        'notes' => self::TABS['notes'] . self::FIELDS['rowDescription'],
        'language' => self::TABS['language'] . self::PALETTES['language'],
        'categories' => self::TABS['categories'] . self::FIELDS['categories'],
    ];

    /**
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     */
    public function __construct(
        protected string $extKey,
        protected string $identifier = '',
        protected string $cTypeLabel = '',
        protected string $icon = '',
        protected string $description = '',
        protected array $palettes = [],
        protected array $columns = [],
        protected string $showItem = '',
        protected Mode $showitemMode = Mode::Default,
        protected array $columnsOverrides = [],
        protected bool $autogenerateTsConfig = true,
        protected bool $autogenerateTyposcript = true,
        protected bool $autogenerateDataProcessors = true,
        protected string $tsConfigFceGroupIdentifier = 'default',
        protected array $additionalTypeConfig = [],
        protected array $dataProcessorFields = [],
    ) {
        $this->cTypeLabel = $this->cTypeLabel ?: $identifier . '.title';
        $this->icon = $this->icon ?: 'ce-' . $identifier;
        $this->description = $this->description ?: $identifier . '.description';
    }

    public function withIdentifier(string $identifier = ''): static
    {
        $this->identifier = $identifier;
        return $this;
    }

    public function withCTypeLabel(string $cTypeLabel = ''): static
    {
        $this->cTypeLabel = $cTypeLabel;
        return $this;
    }

    public function withIcon(string $icon = ''): static
    {
        $this->icon = $icon;
        return $this;
    }

    public function withPalettes(array $palettes = []): static
    {
        $this->palettes = $palettes;
        return $this;
    }

    public function withAdditionalTypeConfig(array $additionalTypeConfig = []): static
    {
        $this->additionalTypeConfig = $additionalTypeConfig;
        return $this;
    }

    /**
     * @throws InvalidKeyException
     * @param list<AbstractShortcut|array> $columns
     */
    public function withColumns(array $columns): static
    {
        $this->columns = [];
        foreach ($columns as $key => $column) {
            $this->addColumn($column, $key);
        }

        return $this;
    }

    public function withShowItem(string ...$showitem): static
    {
        $showitem = implode(',', $showitem);
        $this->showItem = static::withSeparatorAppended($showitem);
        return $this;
    }

    public function withShowitemMode(Mode $showitemMode = Mode::Default): static
    {
        $this->showitemMode = $showitemMode;
        return $this;
    }

    public function withColumnsOverrides(array $columnsOverrides = []): static
    {
        $this->columnsOverrides = $columnsOverrides;
        return $this;
    }

    /**
     * Registers native/pre-existing tt_content fields (e.g. image, media, assets) for automatic
     * FilesProcessor generation, without declaring them as TCA columns via withColumns(). Use this
     * for fields that already exist in tt_content's core TCA and are only tweaked via
     * withColumnsOverrides() - those never reach generateDataProcessors() otherwise.
     *
     * @param array<int|string, string> $fields Either ['fieldName'] to alias 'as' to the field name
     *  itself, or ['fieldName' => 'as'] to alias 'as' to a different Fluid variable name.
     */
    public function withDataProcessorFields(array $fields): static
    {
        $this->dataProcessorFields = [];
        foreach ($fields as $fieldName => $as) {
            $key = is_int($fieldName) ? $as : $fieldName;
            $alias = is_int($fieldName) ? null : $as;
            $this->dataProcessorFields[$key] = new FileShortcut($key, as: $alias);
        }

        return $this;
    }

    public function withoutTyposcript(): static
    {
        $this->autogenerateTyposcript = false;
        return $this;
    }

    public function withoutTsConfig(): static
    {
        $this->autogenerateTsConfig = false;
        return $this;
    }

    public function withoutDataProcessors(): static
    {
        $this->autogenerateDataProcessors = false;
        return $this;
    }

    public function withGroup(string $identifier): static
    {
        $this->tsConfigFceGroupIdentifier = $identifier;
        return $this;
    }

    /**
     * @throws InvalidKeyException
     */
    public function addColumn(AbstractShortcut | array $column, string | int | null $key = null): void
    {
        if (is_string($key) === false) {
            if ($column instanceof AbstractShortcut) {
                $key = $column->getIdentifier();
            } elseif (isset($column['_identifier'])) {
                $key = $column['_identifier'];
            } else {
                throw new InvalidKeyException('Missing key for TCA column', 1724323278);
            }
        }

        $this->columns[$key] = $column;
    }

    /**
     * @throws InvalidKeyException
     * @param list<AbstractShortcut|array> $columns
     */
    public function addColumns(array $columns): void
    {
        foreach ($columns as $key => $column) {
            $this->addColumn($column, $key);
        }
    }

    /**
     * @throws NoIdentifierException
     * @throws TsConfigExistsException
     * @throws TyposcriptExistsException
     * @throws CacheInstanceException
     */
    public function registerFCE(): void
    {
        if ($this->identifier === '') {
            throw new NoIdentifierException();
        }

        ExtensionManagementUtility::addTCAcolumns(
            self::CONTENT_TABLE,
            AbstractShortcut::buildAll($this->columns, self::CONTENT_TABLE),
        );
        ExtensionManagementUtility::addTcaSelectItem(
            self::CONTENT_TABLE,
            'CType',
            [
                'label' => $this->getLabel(),
                'value' => $this->identifier,
                'icon' => $this->icon,
                'group' => $this->tsConfigFceGroupIdentifier,
                'description' => $this->description,
            ],
        );

        $ttContentExtend = $this->buildTtContentExtend();
        ArrayUtility::mergeRecursiveWithOverrule($GLOBALS['TCA'], $ttContentExtend);

        if ($this->autogenerateTsConfig) {
            $this->generateTsConfig();
        }

        if ($this->autogenerateTyposcript) {
            $this->generateTyposcript();
        }

        TcaGenerator::resetItemConfig();
    }

    /**
     * Function uses exit(0), because otherwise no output is generatedfce
     * @SuppressWarnings(PHPMD.ExitExpression)
     */
    public function debugRegisteringFCE(): void
    {
        if ($this->autogenerateTsConfig) {
            $this->generateTsConfig();
        }

        if ($this->autogenerateTyposcript) {
            $this->generateTyposcript();
        }

        $variable = [
            'ExtensionManagementUtility::addTCAcolumns' => [
                self::CONTENT_TABLE,
                $this->columns,
            ],
            'ExtensionManagementUtility::addTcaSelectItem' => [
                self::CONTENT_TABLE,
                'CType',
                [
                    $this->getLabel(),
                    $this->identifier,
                    $this->icon,
                ],
            ],
            'ArrayUtility::mergeRecursiveWithOverrule' => [
                $GLOBALS['TCA'],
                $this->buildTtContentExtend(),
            ],
            'TcaGenerator::getTsConfigData' => [
                TcaGenerator::getTsConfigData(),
            ],
            'TcaGenerator::getTyposcriptData' => [
                TcaGenerator::getTyposcriptData(),
            ],
        ];

        $title = $this->identifier;
        DebuggerUtility::var_dump($variable, $title, 16);
        exit(0);
    }

    protected function buildTtContentExtend(): array
    {
        return [
            self::CONTENT_TABLE => [
                'ctrl' => [
                    'typeicon_classes' => [
                        $this->identifier => $this->icon,
                    ],
                ],
                'palettes' => $this->palettes,
                'types' => [
                    $this->identifier => [
                        'showitem' => static::generateShowitem($this->showItem, $this->showitemMode),
                        'columnsOverrides' => $this->columnsOverrides,
                        ...$this->additionalTypeConfig,
                    ],
                ],
            ],
        ];
    }

    /**
     * @throws TsConfigExistsException
     * @throws CacheInstanceException
     */
    protected function generateTsConfig(): void
    {
        if (!TcaGenerator::getTsConfigData()->hasFceGroup($this->tsConfigFceGroupIdentifier)) {
            TcaGenerator::getTsConfigData()->addFceGroup(
                $this->tsConfigFceGroupIdentifier,
                new FceGroup($this->tsConfigFceGroupIdentifier),
            );
        }

        if (!TcaGenerator::getTsConfigData()->hasFceItem($this->identifier)) {
            TcaGenerator::getTsConfigData()->addFceItem(
                $this->identifier,
                new TsConfigItem(
                    $this->identifier,
                    $this->tsConfigFceGroupIdentifier,
                    $this->icon,
                    $this->getLabel(),
                    $this->getDescription(),
                ),
            );
        }
    }

    /**
     * @throws TyposcriptExistsException
     * @throws CacheInstanceException
     */
    protected function generateTyposcript(): void
    {
        $dataProcessors = [];
        if ($this->autogenerateDataProcessors) {
            $dataProcessors = $this->generateDataProcessors();
        }

        if (!TcaGenerator::getTyposcriptData()->hasBaseFceItemFor($this->extKey)) {
            TcaGenerator::getTyposcriptData()->addBaseFceItemFor($this->extKey);
        }

        if (!TcaGenerator::getTyposcriptData()->hasFceItem($this->identifier)) {
            TcaGenerator::getTyposcriptData()->addFceItem(
                $this->identifier,
                new TyposcriptItem(
                    $this->identifier,
                    null,
                    TcaGenerator::getTyposcriptData()->getBaseFceItemFor($this->extKey),
                    $dataProcessors,
                ),
            );
        }
    }

    protected function generateDataProcessors(): array
    {
        return DataProcessorUtility::generate([...$this->columns, ...$this->dataProcessorFields]);
    }

    protected function getLabel(): string
    {
        if (str_starts_with($this->cTypeLabel, 'LLL:')) {
            return $this->cTypeLabel;
        }

        if ($this->cTypeLabel !== '') {
            return static::getLocalizedLabel($this->cTypeLabel);
        }

        return $this->identifier;
    }

    protected function getDescription(): string
    {
        if (str_starts_with($this->description, 'LLL:')) {
            return $this->description;
        }

        if ($this->description !== '') {
            return static::getLocalizedLabel($this->description);
        }

        return $this->description;
    }

    protected static function getLocalizedLabel(string $label): string
    {
        return TcaGenerator::getConfig()->ll() . self::CONTENT_TABLE . '.' . $label;
    }

    protected static function generateShowitem(string $showitem, Mode $showitemMode): string
    {
        return match ($showitemMode) {
            Mode::Default => static::showitemDefault($showitem),
            Mode::DefaultNoHeader => static::showitemDefaultNoHeader($showitem),
            Mode::DefaultNoHeaderNoAppearance => static::showitemDefaultNoHeaderNoAppearance($showitem),
            Mode::Override => $showitem,
        };
    }

    protected static function showitemDefault(string $showitem): string
    {
        return
            self::JOINED['generalPrepend'] .
            $showitem .
            self::JOINED['appearance'] .
            self::JOINED['language'] .
            self::JOINED['access'] .
            self::JOINED['categories'] .
            self::JOINED['notes'] .
            self::TABS['extended'];
    }

    protected static function showitemDefaultNoHeader(string $showitem): string
    {
        return
            self::TABS['general'] .
            self::PALETTES['general'] .
            $showitem .
            self::JOINED['appearance'] .
            self::JOINED['language'] .
            self::JOINED['access'] .
            self::JOINED['categories'] .
            self::JOINED['notes'] .
            self::TABS['extended'];
    }

    protected static function showitemDefaultNoHeaderNoAppearance(string $showitem): string
    {
        return
            self::TABS['general'] .
            self::PALETTES['general'] .
            $showitem .
            self::JOINED['language'] .
            self::JOINED['access'] .
            self::JOINED['categories'] .
            self::JOINED['notes'] .
            self::TABS['extended'];
    }

    protected static function withSeparatorAppended(string $showitem): string
    {
        return $showitem . (str_ends_with(trim($showitem), ',') ? '' : ',');
    }
}
